### ISSUE TITLE
Compatible with iOS6?

### ISSUE THREAD

**Issue by dkrusenstrahle** [collectiveidea/rubymotion-drawing#1]
Hello,

I downloaded and implemented your code in my Rubymotion project and it works, kind of, when I draw with my fingers on the screen it looks like the iPhone have a virus :) All kinds of colors and shapes appear and jump around. I have used your exact code. Not sure if it´s a compatible issue. I use iOS 6.

Any clues?

Thanks!

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
